# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/ETH_1000BASEX.xci
# IP: The module: 'ETH_1000BASEX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/ETH_1000BASEX_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/synth/ETH_1000BASEX.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/synth/ETH_1000BASEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/ETH_1000BASEX.xci
# IP: The module: 'ETH_1000BASEX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/ETH_1000BASEX_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/synth/ETH_1000BASEX.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DELL/Desktop/mft_k7_project/9.26/project_1_cppf_sitcp/project_1_cppf_sitcp.srcs/sources_1/ip/ETH_1000BASEX/synth/ETH_1000BASEX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ETH_1000BASEX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
